-- CreateTable
CREATE TABLE "RawData" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "dataSchemaVersion" TEXT NOT NULL,
    "ingestedBy" TEXT NOT NULL,
    "priority" TEXT NOT NULL,
    "lastAccessed" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
